// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmxmmmyzcwhszxgloqas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNteG1tbXl6Y3doc3p4Z2xvcWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MjM4MjIsImV4cCI6MjA1NjI5OTgyMn0.ivHizycFb6LFb8534UwL4Eg0nn_qwgOpbF0j24j5pAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);